### ISSUE TITLE
BUG previous click and forward click

### ISSUE THREAD

**Issue by ZiipX** [AzPepoze/Newtube#1]
when i try to click previous button, my youtube is like reload again and again or when i try to click youtube video link from google or twitter or any website, my youtube is like reload again and again, it's not loading, but it is like refreshing page again and again.

**Comment by AzPepoze** [comment]
What browser do you using?

**Comment by ZiipX** [comment]
google chrome

**Comment by AzPepoze** [comment]
Have you tried disabling my extensions?

I want to make sure it's caused by my extention.
