### ISSUE TITLE
BUG: on video page load and in player

### ISSUE THREAD

**Issue by lycanknight** [AzPepoze/Newtube#3]
### **Issue One:**
I've noticed today that when i open a video on YouTube when it loads everything is invisible from the video, comments, and the side thumbnails until i click where the video is supposed to be and i only really know this thanks to the borders that i set up using the extension stayed and showed once i click the video location everything shows back up and i used the enable button inside the setting and turned the extension off instead of out right disabling it in extensions when it was all invisible and and it showed back up the second i turned it off but went away again once i turned it back on i even tried to reset it and use blank settings but that did not help but once you click where the vide is and things show they stay until you load a new video and now for issue two

### **Issue Two:**
also recently the control panel in the video player will hide itself and never come back without reloading the page a few time if your lucky this one i'm not 100% sure is to blame on this extension but it did start happening around the same time as issue one 

(i am on Brave Browser as far as i know latest version) any help would be awesome please and thank you for any help you're able to provide

**Comment by AzPepoze** [comment]
Has it been solved yet? (Sorry for too late,Mostly I use discord to recive bug report so sorry)

**Comment by AzPepoze** [comment]
-
