### ISSUE TITLE
Q: customised this and somehow i have selected category white?

### ISSUE THREAD

**Issue by Makezu90** [AzPepoze/Newtube#4]
How i can select different color? i tried theme colors but did not find way choose it, mine text color is white so can't see what is selected .. 
![image](https://github.com/AzPepoze/Newtube/assets/89158176/c0ba3833-13fe-47ab-94f0-41faf645074e)

**Comment by AzPepoze** [comment]
Oh thx for the report.I'll fix this soon! 😊😊😊

**Comment by AzPepoze** [comment]
Fixed :D Is that work?

**Comment by Makezu90** [comment]
> Fixed :D Is that work?

yes, thanks 👍 🙂
